server:
  port: 8081

spring:
  application:
    name: license-service
  datasource:
    url: jdbc:h2:file:./license-db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin123

license:
  secret-key: "CatasoftLicenseSecretKey2024"
  algorithm: "AES"
  fingerprint-salt: "CatasoftFingerprintSalt2024"
  validation-interval: 86400 # 24 horas en segundos

logging:
  level:
    com.catasoft.license: DEBUG
    org.springframework.security: DEBUG 